# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT


# Mod Properties
mod_version=1.5.1
maven_group=tech.showierdata
archives_base_name=pickaxe

# Dependencies
fabric_version=0.159.0+26.2
yacl_version=3.9.6
modmenu_version=20.0.1
imguimc_version=2.0.5
sqlite_version=3.53.4.0